---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  environments_path: ./environments

platforms:
  - name: ubuntu-12.04
    run_list: apt::default
  #- name: centos-6.4

suites:
  - name: default
    provisioner:
      solo_rb:
        environment: test
    run_list:
      - recipe[webserver::default]
    attributes:
