source 'https://rubygems.org'

gem 'berkshelf'

# Uncomment these lines if you want to live on the Edge:
#
# group :development do
#   gem "berkshelf", github: "berkshelf/berkshelf"
#   gem "vagrant", github: "mitchellh/vagrant", tag: "v1.6.3"
# end
#
# group :plugins do
#   gem "vagrant-berkshelf", github: "berkshelf/vagrant-berkshelf"
#   gem "vagrant-omnibus", github: "schisamo/vagrant-omnibus"
# end

gem 'foodcritic'
gem 'fauxhai'
gem 'chefspec'
gem 'busser-bats'
gem 'busser-minitest'
group :integration do
    gem 'kitchen-vagrant'
end

# group :development do
    # gem 'foodcritic'
    # gem 'fauxhai'
    # gem 'chefspec'
    # gem 'busser-bats'
    # gem 'busser-minitest'
    # gem 'kitchen-vagrant'
# end